const nodemailer = require('nodemailer');

const createTransporter = () => {
  return nodemailer.createTransport({
    host: process.env.EMAIL_HOST || 'smtp.gmail.com',
    port: parseInt(process.env.EMAIL_PORT || '587', 10),
    secure: false, // STARTTLS
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS,
    },
  });
};

/**
 * Send the AI-generated executive summary to the recipient's email.
 * @param {string} to - Recipient email address
 * @param {string} summary - The Gemini-generated executive summary text
 */
const sendSummaryEmail = async (to, summary) => {
  const transporter = createTransporter();

  const htmlBody = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Sales Insight Report</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700&family=DM+Mono:wght@300;400&display=swap');

    body {
      margin: 0;
      padding: 0;
      background-color: #040810;
      font-family: 'DM Mono', monospace;
      color: #c8d8e8;
    }

    .wrapper {
      max-width: 680px;
      margin: 0 auto;
      padding: 40px 20px;
    }

    .header {
      text-align: center;
      padding: 40px 30px;
      background: linear-gradient(135deg, rgba(0,255,180,0.08), rgba(0,200,255,0.08));
      border: 1px solid rgba(0,255,180,0.25);
      border-radius: 16px;
      margin-bottom: 30px;
    }

    .logo {
      font-family: 'Orbitron', sans-serif;
      font-size: 22px;
      font-weight: 700;
      color: #00ffb4;
      letter-spacing: 3px;
      text-transform: uppercase;
      margin-bottom: 8px;
    }

    .subtitle {
      font-size: 12px;
      color: #00c8ff;
      letter-spacing: 2px;
      text-transform: uppercase;
    }

    .badge {
      display: inline-block;
      background: rgba(0,255,180,0.1);
      border: 1px solid rgba(0,255,180,0.3);
      color: #00ffb4;
      padding: 4px 14px;
      border-radius: 20px;
      font-size: 11px;
      letter-spacing: 1px;
      margin-top: 12px;
    }

    .card {
      background: rgba(255,255,255,0.03);
      border: 1px solid rgba(0,200,255,0.2);
      border-radius: 16px;
      padding: 32px;
      margin-bottom: 20px;
    }

    .card-title {
      font-family: 'Orbitron', sans-serif;
      font-size: 13px;
      color: #00c8ff;
      letter-spacing: 2px;
      text-transform: uppercase;
      margin-bottom: 20px;
      padding-bottom: 12px;
      border-bottom: 1px solid rgba(0,200,255,0.15);
    }

    .summary-text {
      font-size: 14px;
      line-height: 1.9;
      color: #c8d8e8;
      white-space: pre-wrap;
    }

    .footer {
      text-align: center;
      padding: 24px;
      font-size: 11px;
      color: rgba(255,255,255,0.3);
      letter-spacing: 1px;
    }

    .glow-line {
      height: 1px;
      background: linear-gradient(90deg, transparent, #00ffb4, #00c8ff, transparent);
      margin: 30px 0;
      opacity: 0.4;
    }
  </style>
</head>
<body>
  <div class="wrapper">
    <div class="header">
      <div class="logo">⚡ RabbitAI</div>
      <div class="subtitle">Sales Insight Command Center</div>
      <div class="badge">MISSION REPORT READY</div>
    </div>

    <div class="card">
      <div class="card-title">📊 Executive Intelligence Summary</div>
      <div class="summary-text">${summary.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</div>
    </div>

    <div class="glow-line"></div>

    <div class="footer">
      <p>Generated by RabbitAI Sales Insight Automator</p>
      <p>Powered by Google Gemini 1.5 Flash · ${new Date().toUTCString()}</p>
    </div>
  </div>
</body>
</html>`;

  const mailOptions = {
    from: `"RabbitAI Command Center" <${process.env.EMAIL_USER}>`,
    to,
    subject: '🚀 Your Sales Intelligence Report is Ready — RabbitAI',
    text: `Sales Insight Executive Summary\n\n${summary}`,
    html: htmlBody,
  };

  await transporter.sendMail(mailOptions);
};

module.exports = { sendSummaryEmail };
